DB changes  for user details
prafullmaru/ePanchayat pull request #18
Opened 2024-06-19 05:19 UTC by RiteshKolhe

Captured the qualification and vehicle.

2024-06-19 06:00 UTC, mohandivraniya requested changes
Please address issues:
1. Add constraints to manage data efficiently
2. Include Joins while fetching details
3. Address nullable fields

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/Tables/DDL/House_tbl.sql
> +)
Let we please add all related constraint for Primary key, foreign key, default etc.

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/Tables/DDL/Qualification_tbl.sql
> +)
Same here - please add all required constraints

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/StoredProcedures/HouseGet_sp.sql
> +		dbo.House_tbl
Let we perform join with user_tbl to get user details also for Owner and ModifiedBy user.

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/StoredProcedures/HouseSave_sp.sql
> +	@HouseId INT
Fields can be nullable while doing insert, Also fields like Landmark will null

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/StoredProcedures/QualificationGet_sp.sql
> +		dbo.Qualification_tbl
Same here - Perform join while fetching data

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/StoredProcedures/VehicleGet_sp.sql
> +		dbo.Vehicle_tbl
Perform join to fetch user details

2024-06-19 06:00 UTC, mohandivraniya commented on ePanchayat.DB/StoredProcedures/VehicleSave_sp.sql
> +	@VehicleId INT
Fields can be nullable

2024-06-20 04:50 UTC, RiteshKolhe commented
> Captured the qualification and vehicle.

Addressed the issue

2024-06-20 04:52 UTC, RiteshKolhe commented
> Captured the qualification and vehicle.

It's done

2024-06-20 04:59 UTC, mohandivraniya approved these changes

2024-06-20 05:05 UTC, merged